newfold-labs/wp-module-installer

includes/Data/Options.php, includes/Data/Plugins.php, includes/Models/PriorityQueue.php, includes/Permissions.php, includes/RestApi/PluginsController.php, includes/RestApi/RestApi.php, includes/Services/PluginInstaller.php, includes/Services/PluginUninstaller.php, includes/TaskManagers/PluginInstallTaskManager.php, includes/TaskManagers/PluginUninstallTaskManager.php, includes/TaskManagers/TaskManager.php, includes/Tasks/PluginInstallTask.php, includes/Tasks/PluginUninstallTask.php
Changes from functionality available in `@newfold-labs/wp-module-onboarding`
- Disable Theme Installation controller
- No SiteFeatures API
- No auto install of plugins based on brand configuration
=> Update Plugin Installation Flow

bootstrap.php, composer.lock
=> Bump Installer to 1.1.4

LICENSE, README.md
=> Update documentation and add license information

includes/Data/Plugins.php
Added support for toggling Jetpack modules. 
Jetpack API : https://github.com/Automattic/jetpack/blob/trunk/docs/rest-api.md#post-wp-jsonjetpackv4settings
Jira Ticket : https://jira.newfold.com/browse/PRESS0-1578
=> Added method to toggle jetpack modules

src/Scripts/dataAttrListener.js
=> Update PLS data attributes

src/Installer/components/Modal/index.jsx
=> Add free plugin installation

src/Installer/components/App/index.jsx, src/Scripts/dataAttrListener.js
=> Fix free plugin checks

composer.json, composer.lock, includes/Data/Constants.php, package-lock.json, package.json
=> Update build to 1.2.0

README.md, includes/Data/Constants.php
The JS changes are not loaded cause there is a version mismatch and the path it tries to find doesn't exist.
=> Fix Version Mismatch

.github/workflows/lint-check-spa.yml, .github/workflows/lint.yml
This PR will update the actions/cache to version 4 to prevent workflow failures.
=> Update actions/cache to version 4

package-lock.json, package.json, set-version-bump.js
Add set-version-bump script and dependencies
=> Add set-version-bump script

.github/workflows/brand-plugin-test.yml
Adds the workflow for running plugin tests in module PRs.
=> add test workflow

includes/Data/Plugins.php
This PR adds Jetpack Protect to the install whitelist for use in malware checks within the Hosting Panel dashboard.
=> Hosting Panel: Add Jetpack Protect

includes/Data/Constants.php, package-lock.json, package.json
=> Bump version to 1.4.2

includes/Data/Themes.php
Add Bluehost Blueprint theme installer reference.
=> Blueprint theme

includes/Data/Constants.php, package-lock.json, package.json
Minor release that include the new Blueprint theme source ref: https://github.com/newfold-labs/wp-module-installer/pull/100
=> Release v1.4.4

includes/RestApi/PluginsController.php, includes/Services/PluginInstaller.php, src/Installer/components/Modal/index.jsx, src/Scripts/dataAttrListener.js
Pass the basename attribute into the modal and install post requests when possible.
=> Add plugin basename attribute

includes/RestApi/PluginsController.php
We're only sending the premium param when true, so this was logging debug error when not set. The update will default to false if it is not received.
=> default premium value to false

includes/RestApi/PluginsController.php
There are multiple places where plugin installs are initiated. Before triggering the install, we need to first check that the plugin is not already installed and or active. Earlier we added this for premium plugins, but this update will do this for all plugins, and earlier.
There are other places this could go, but this feels the cleanest and most direct. There are other modules that integrate with the installer though so we can't (yet) require the basename value, but the solutions module sends this data in. If it exists, we can use it to quickly detect if the plugin in question is already installed, and if so if it is already active too.
The `PluginInstaller::install_premium_plugin` method was updated earlier to perform similarly. We could also look at these:
- PluginInstaller::install
- …
=> check if plugin installed/active in controller

includes/Data/Plugins.php
By default YOAST performs a redirect to a page of own panel after the activation. This creates a conflict with the Bluehost site creation so this PR wants prevent the redirect on YOAST side and avoid any issue.
=> Prevent redirect to admin page of YOAST after plugin installation

languages/wp-module-installer-de_DE-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-de_DE.po, languages/wp-module-installer-en_AU-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-en_AU.po, languages/wp-module-installer-en_GB-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-en_GB.po, languages/wp-module-installer-es_ES-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-es_ES.po, languages/wp-module-installer-es_MX-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-es_MX.po, languages/wp-module-installer-fr_FR-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-fr_FR.po, languages/wp-module-installer-it_IT-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-it_IT.po, languages/wp-module-installer-nl_NL-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-nl_NL.po, languages/wp-module-installer-pt_BR-4eca237e884111cf8deb52cfa44297cb.json, languages/wp-module-installer-pt_BR.po, languages/wp-module-installer.pot
This PR updates the i18n translation files.
=> Update i18n translation files
